### ISSUE TITLE
Issues with lists and sets

### ISSUE THREAD

**Issue by ferdieperante** [hannesfrank/remnote-css-rem-types#3]
With Custom CSS: 
![With Custom CSS](https://user-images.githubusercontent.com/21334837/110196962-21558380-7e83-11eb-9d01-697cbbd724f8.jpg)
Without Custom CSS: 
![Without Custom CSS](https://user-images.githubusercontent.com/21334837/110196967-24507400-7e83-11eb-8166-360f8ae10856.jpg)

**Comment by hannesfrank** [comment]
![image](https://user-images.githubusercontent.com/4137110/110236315-60441180-7f35-11eb-9933-2d86223f88c8.png)

Fixed in e31c8b4914282907c26d86d976da057118c7adc4
